question_data = [
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Books",
	 "question": "Originally, the character Charlie from Charlie and the Chocolate Factory was going to be black.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "hard", "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "In the &quot;To Love-Ru&quot; series, Peke is considered a female robot.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Science: Mathematics",
	 "question": "Zero factorial is equal to zero. ", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
	 "question": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen Beetle in the background.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
	 "question": "In &quot;Overwatch,&quot; an allied McCree will say &quot;Step right up&quot; upon using his ultimate ability Deadeye.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Board Games",
	 "question": "In the game &quot;Racko&quot; you may pick up ANY card from the discard pile.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "History",
	 "question": "Adolf Hitler was a german soldier in World War I.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "History",
	 "question": "Martin Luther King Jr. and Anne Frank were born the same year. ",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Cartoon &amp; Animations",
	 "question": "Nutcracker Suite was one of the musical pieces featured in Disney&#039;s 1940&#039;s film Fantasia.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Science: Computers",
	 "question": "The Windows 7 operating system has six main editions.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
	 "question": "Actor Tommy Chong served prison time.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Sports",
	 "question": "Soccer player Cristiano Ronaldo opened a museum dedicated to himself.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
	 "question": "The video game &quot;Fuel&quot; has an open world that is 5,560 square miles?",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "Minecraft can be played with a virtual reality headset.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Animals",
	 "question": "A flock of crows is known as a homicide.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "Pac-Man was invented by the designer Toru Iwatani while he was eating pizza.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "The game &quot;Jetpack Joyride&quot; was created by &quot;Redbrick Studios&quot;.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "The game &quot;Pocket Morty&quot; has a Morty called &quot;Pocket Mortys Morty&quot;?",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "hard", "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "The protagonist in &quot;Humanity Has Declined&quot; has no discernable name and is simply referred to as &#039;I&#039; for most of the series.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "hard", "category": "History",
	 "question": "The Battle of Trafalgar took place on October 23rd, 1805", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Geography",
	 "question": "A group of islands is called an &#039;archipelago&#039;.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Vehicles",
	 "question": "The majority of Subaru vehicles are made in China.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "hard", "category": "Entertainment: Video Games",
	 "question": "In The Witcher 3, the Zoltan Chivay Gwent card can be found under the Hanged Man&#039;s Tree.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "General Knowledge",
	 "question": "The Lego Group was founded in 1932.", "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
	 "question": "Metal Gear Solid V: The Phantom Pain runs on the Fox Engine.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "Ana was added as a new hero for the game Overwatch on July 19th, 2016.", "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Science: Computers",
	 "question": "The first computer bug was formed by faulty wires.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "The name of the attack &quot;Kamehameha&quot; in Dragon Ball Z was named after a famous king of Hawaii.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Television",
	 "question": "An episode of &quot;The Simpsons&quot; is dedicated to Moe Szyslak&#039;s bar rag.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
	 "question": "In career mode of &quot;Need for Speed: Underground 2&quot;, the first car the player can drive is the BMW M3 GTR.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Geography",
	 "question": "New Haven is the capital city of the state of Connecticut in the United States.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Japanese Anime &amp; Manga",
	 "question": "Clefairy was intended to be Ash&#039;s starting Pok&eacute;mon in the pilot episode of the cartoon.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Film",
	 "question": "In the original Star Wars trilogy, David Prowse was the actor who physically portrayed Darth Vader.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Politics",
	 "question": "During the 2016 United States presidential election, the State of California possessed the most electoral votes, having 55.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
	 "question": "&quot;Return to Castle Wolfenstein&quot; was the only game of the Wolfenstein series where you don&#039;t play as William &quot;B.J.&quot; Blazkowicz.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Animals",
	 "question": "The Axolotl is an amphibian that can spend its whole life in a larval state.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Video Games",
	 "question": "There are 2 player roles in Trouble in Terrorist Town.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "easy", "category": "Animals",
	 "question": "Cats have whiskers under their legs.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Entertainment: Cartoon &amp; Animations",
	 "question": "In the &quot;Shrek&quot; film franchise, Donkey is played by Eddie Murphy.",
	 "correct_answer": "True",
	 "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
	 "question": "Rapper Snoop Dogg&#039;s real name is &#039;Cordozar Calvin Broadus, Jr.&#039;.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Geography",
	 "question": "Ottawa is the capital of Canada.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "Science &amp; Nature",
	 "question": "An average human can go two weeks without water.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "hard", "category": "Science: Computers",
	 "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "History",
	 "question": "Adolf Hitler was accepted into the Vienna Academy of Fine Arts.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "Sports",
	 "question": "Wilt Chamberlain scored his infamous 100-point-game against the New York Knicks in 1962.",
	 "correct_answer": "True", "incorrect_answers": ["False"]},
	{"type": "boolean", "difficulty": "easy", "category": "History",
	 "question": "Adolf Hitler was tried at the Nuremberg trials.", "correct_answer": "False",
	 "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Music",
	 "question": "Soulja Boy&#039;s &#039;Crank That&#039; won a Grammy for Best Rap Song in 2007.",
	 "correct_answer": "False", "incorrect_answers": ["True"]},
	{"type": "boolean", "difficulty": "medium", "category": "Entertainment: Video Games",
	 "question": "The game Garry&#039;s Mod originally took assets and codes from the popular Half Life 2 mod JBmod.",
	 "correct_answer": "True", "incorrect_answers": ["False"]}]
